const routes = [
  { path: '/', 
  component: () => import('layouts/AuthenticationLayout.vue'),
  children: [
    { path: '/', component: () => import('pages/authentication/loginregister.vue') },
    { path: '/home', component: () => import('pages/home/index.vue') },
    { path: '/about', component: () => import('pages/home/aboutus.vue') },
    { path: '/categories', component: () => import('pages/home/categories.vue') },
    { path: '/categoryN500Levels', component: () => import('pages/home/categoryN500Levels.vue') },
    { path: '/categoryN1000Levels', component: () => import('pages/home/categoryN1000Levels.vue') },
    { path: '/categoryN2000Levels', component: () => import('pages/home/categoryN2000Levels.vue') },
    { path: '/categoryN5000Levels', component: () => import('pages/home/categoryN5000Levels.vue') },
    { path: '/categoryN10000Levels', component: () => import('pages/home/categoryN10000Levels.vue') },
    { path: '/login_register', component: () => import('pages/authentication/loginregister.vue') },
    { path: '/skills-aquisition', component: () => import('pages/home/skillAquisition.vue') },
  ] },
  {
    path: '/user-home',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '/user-home', component: () => import('pages/home/index.vue') },
      { path: '/user-about', component: () => import('pages/home/aboutus.vue') },
      { path: '/user-categories', component: () => import('pages/home/categories.vue') },
      { path: '/user-categoryN500Levels', component: () => import('pages/home/categoryN500Levels.vue') },
      { path: '/user-categoryN1000Levels', component: () => import('pages/home/categoryN1000Levels.vue') },
      { path: '/user-categoryN2000Levels', component: () => import('pages/home/categoryN2000Levels.vue') },
      { path: '/user-categoryN5000Levels', component: () => import('pages/home/categoryN5000Levels.vue') },
      { path: '/user-categoryN10000Levels', component: () => import('pages/home/categoryN10000Levels.vue') },
      { path: '/user-team', component: () => import('pages/home/teams.vue') },
      { path: '/user-contact', component: () => import('pages/authentication/contactData.vue') },
      { path: '/user-biodata', component: () => import('pages/authentication/bioData.vue') },
      { path: '/user-bankdetails', component: () => import('pages/authentication/bankAccountData.vue') },
      { path: '/user-nextofkin', component: () => import('pages/authentication/nextOfKinData.vue') },
      { path: '/user-contribution', component: () => import('pages/contribution/contribute.vue') },
      { path: '/user-dashboard', component: () => import('pages/dashboard/dashboard.vue') },
      { path: '/user-createCategoryN500', component: () => import('pages/administrators/CategoryN500Admin/CreateCategoryN500.vue') },
      { path: '/user-createCategoryN1000', component: () => import('pages/administrators/CategoryN1000Admin/CreateCategoryN1000.vue') },
      { path: '/user-createCategoryN2000', component: () => import('pages/administrators/CategoryN2000Admin/CreateCategoryN2000.vue') },
      { path: '/user-createCategoryN5000', component: () => import('pages/administrators/CategoryN5000Admin/CreateCategoryN5000.vue') },
      { path: '/user-createCategoryN10000', component: () => import('pages/administrators/CategoryN10000Admin/CreateCategoryN10000.vue') },
      { path: '/faqs', component: () => import('pages/dashboard/faq.vue') },
      { path: '/unread-messages', component: () => import('pages/administrators/chat/landing.vue') },
      { path: '/view-chat', component: () => import('pages/administrators/chat/viewCreateChat.vue') },
    ]
  },
  {
    path: '/admin',
    component: () => import('layouts/AdminLayout.vue'),
    children: [
      { path: '/admin', component: () => import('pages/home/index.vue') },
      { path: '/administrators', component: () => import('pages/administrators/Administrators.vue') },
      { path: '/register-administrator', component: () => import('pages/administrators/CreateAdmin.vue') },
      { path: '/update-administrator', component: () => import('pages/administrators/UpdateAdmin.vue') },
      { path: '/confirmEntryPaymentN500', component: () => import('pages/administrators/AccountN500Admin/unconfirmedAccountsN500.vue') },
      { path: '/confirmEntryPaymentN1000', component: () => import('pages/administrators/AccountN1000Admin/unconfirmedAccountsN1000.vue') },
      { path: '/confirmEntryPaymentN2000', component: () => import('pages/administrators/AccountN2000Admin/unconfirmedAccountsN2000.vue') },
      { path: '/confirmEntryPaymentN5000', component: () => import('pages/administrators/AccountN5000Admin/unconfirmedAccountsN5000.vue') },
      { path: '/confirmEntryPaymentN10000', component: () => import('pages/administrators/AccountN10000Admin/unconfirmedAccountsN10000.vue') },
      { path: '/registeredContributors', component: () => import('pages/administrators/ContriubutorsAdmin/registeredContributors.vue') },
      { path: '/register', component: () => import('pages/authentication/personalData.vue') },
      { path: '/comfirmPaymentN500', component: () => import('pages/administrators/AccountN500Admin/comfirmpaymentN500.vue') },
      { path: '/comfirmPaymentN1000', component: () => import('pages/administrators/AccountN1000Admin/comfirmpaymentN1000.vue') },
      { path: '/comfirmPaymentN2000', component: () => import('pages/administrators/AccountN2000Admin/comfirmpaymentN2000.vue') },
      { path: '/comfirmPaymentN5000', component: () => import('pages/administrators/AccountN5000Admin/comfirmpaymentN5000.vue') },
      { path: '/comfirmPaymentN10000', component: () => import('pages/administrators/AccountN10000Admin/comfirmpaymentN10000.vue') },
      { path: '/confirmCategoryN500LevelPayment', component: () => import('pages/administrators/AccountN500Admin/confirmLevelPaymentN500.vue') },
      { path: '/confirmCategoryN1000LevelPayment', component: () => import('pages/administrators/AccountN1000Admin/confirmLevelPaymentN1000.vue') },
      { path: '/confirmCategoryN2000LevelPayment', component: () => import('pages/administrators/AccountN2000Admin/confirmLevelPaymentN2000.vue') },
      { path: '/confirmCategoryN5000LevelPayment', component: () => import('pages/administrators/AccountN5000Admin/confirmLevelPaymentN5000.vue') },
      { path: '/confirmCategoryN10000LevelPayment', component: () => import('pages/administrators/AccountN10000Admin/confirmLevelPaymentN10000.vue') },
      { path: '/SelectedLevelN500', component: () => import('pages/administrators/AccountN500Admin/SelectedLevelN500.vue') },
      { path: '/SelectedLevelN1000', component: () => import('pages/administrators/AccountN1000Admin/SelectedLevelN1000.vue') },
      { path: '/SelectedLevelN2000', component: () => import('pages/administrators/AccountN2000Admin/SelectedLevelN2000.vue') },
      { path: '/SelectedLevelN5000', component: () => import('pages/administrators/AccountN5000Admin/SelectedLevelN5000.vue') },
      { path: '/SelectedLevelN10000', component: () => import('pages/administrators/AccountN10000Admin/SelectedLevelN10000.vue') },
      { path: '/contacts', component: () => import('pages/administrators/ContriubutorsAdmin/contacts.vue') },
      { path: '/bioData', component: () => import('pages/administrators/ContriubutorsAdmin/bioDatas.vue') },
      { path: '/bankDetails', component: () => import('pages/administrators/ContriubutorsAdmin/bankDetails.vue') },
      { path: '/nextOfKins', component: () => import('pages/administrators/ContriubutorsAdmin/nextOfKins.vue') },
      { path: '/contact', component: () => import('pages/authentication/contactData.vue') },
      { path: '/bio-data', component: () => import('pages/authentication/bioData.vue') },
      { path: '/bankDetail', component: () => import('pages/authentication/bankAccountData.vue') },
      { path: '/nextOfKin', component: () => import('pages/authentication/nextOfKinData.vue') },
      { path: '/makeContributionsN500', component: () => import('pages/administrators/AccountN500Admin/registeredHaveNotContributedN500.vue') },
      { path: '/makeContributionsN1000', component: () => import('pages/administrators/AccountN1000Admin/registeredHaveNotContributedN1000.vue') },
      { path: '/makeContributionsN2000', component: () => import('pages/administrators/AccountN2000Admin/registeredHaveNotContributedN2000.vue') },
      { path: '/makeContributionsN5000', component: () => import('pages/administrators/AccountN5000Admin/registeredHaveNotContributedN5000.vue') },
      { path: '/makeContributionsN10000', component: () => import('pages/administrators/AccountN10000Admin/registeredHaveNotContributedN10000.vue') },
      { path: '/contribute', component: () => import('pages/contribution/contribute.vue') },
      { path: '/cashOutsN500', component: () => import('pages/administrators/AccountN500Admin/cashOutsN500.vue') },
      { path: '/cashOutsN1000', component: () => import('pages/administrators/AccountN1000Admin/cashOutsN1000.vue') },
      { path: '/cashOutsN2000', component: () => import('pages/administrators/AccountN2000Admin/cashOutsN2000.vue') },
      { path: '/cashOutsN5000', component: () => import('pages/administrators/AccountN5000Admin/cashOutsN5000.vue') },
      { path: '/cashOutsN10000', component: () => import('pages/administrators/AccountN10000Admin/cashOutsN10000.vue') },
      { path: '/personalDataCategoryN500s', component: () => import('pages/administrators/CategoryN500Admin/PersonalDataCategoryN500s.vue') },
      { path: '/personalDataCategoryN1000s', component: () => import('pages/administrators/CategoryN1000Admin/PersonalDataCategoryN1000s.vue') },
      { path: '/personalDataCategoryN2000s', component: () => import('pages/administrators/CategoryN2000Admin/PersonalDataCategoryN2000s.vue') },
      { path: '/personalDataCategoryN5000s', component: () => import('pages/administrators/CategoryN5000Admin/PersonalDataCategoryN5000s.vue') },
      { path: '/personalDataCategoryN10000s', component: () => import('pages/administrators/CategoryN10000Admin/PersonalDataCategoryN10000s.vue') },
      { path: '/createCategoryN500', component: () => import('pages/administrators/CategoryN500Admin/CreateCategoryN500.vue') },
      { path: '/createCategoryN1000', component: () => import('pages/administrators/CategoryN1000Admin/CreateCategoryN1000.vue') },
      { path: '/createCategoryN2000', component: () => import('pages/administrators/CategoryN2000Admin/CreateCategoryN2000.vue') },
      { path: '/createCategoryN5000', component: () => import('pages/administrators/CategoryN5000Admin/CreateCategoryN5000.vue') },
      { path: '/createCategoryN10000', component: () => import('pages/administrators/CategoryN10000Admin/CreateCategoryN10000.vue') },
      { path: '/categoryN500Contributors', component: () => import('pages/administrators/CategoryN500Admin/CategoryN500Contributors.vue') },
      { path: '/categoryN1000Contributors', component: () => import('pages/administrators/CategoryN1000Admin/CategoryN1000Contributors.vue') },
      { path: '/categoryN2000Contributors', component: () => import('pages/administrators/CategoryN2000Admin/CategoryN2000Contributors.vue') },
      { path: '/categoryN5000Contributors', component: () => import('pages/administrators/CategoryN5000Admin/CategoryN5000Contributors.vue') },
      { path: '/categoryN10000Contributors', component: () => import('pages/administrators/CategoryN10000Admin/CategoryN10000Contributors.vue') },
      { path: '/viewCashOutN500', component: () => import('pages/administrators/AccountN500Admin/viewCashOutN500.vue') },
      { path: '/viewCashOutN1000', component: () => import('pages/administrators/AccountN1000Admin/viewCashOutN1000.vue') },
      { path: '/viewCashOutN2000', component: () => import('pages/administrators/AccountN2000Admin/viewCashOutN2000.vue') },
      { path: '/viewCashOutN5000', component: () => import('pages/administrators/AccountN5000Admin/viewCashOutN5000.vue') },
      { path: '/viewCashOutN10000', component: () => import('pages/administrators/AccountN10000Admin/viewCashOutN10000.vue') },
    ]
  }
]

// Always leave this as last one
if (process.env.MODE !== 'ssr') {
  routes.push({
    path: '*',
    component: () => import('pages/Error404.vue')
  })
}

export default routes
